#!/system/bin/sh
#
# Created by Calkulin

SD_CARD_SPEED=`cat /sys/devices/virtual/bdi/179:0/read_ahead_kb`

if [ $SD_CARD_SPEED = "4" ]; then
    echo 256 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
    echo "SD Card speed fix was ENABLED"
else
    echo "SD Card speed fix was NOT needed"
fi
